import { NextPage } from 'next';
import Head from 'next/head'
import { useRouter } from 'next/router';
import { useState } from 'react';
// identifica e previne erros 
import Styles from "../scss/home.module.scss"

// renderiza paginas com otimizacao 
const Home: NextPage = () => {
  
  // tipar uma funcao em ts com <>
  const [soma, setSoma] = useState<number>(0);
  
  // gerenciador de rotas = router
  const router = useRouter()
  
  const Somar = (): number => {
    setSoma(soma + 1)  
    return soma
  }
  
  // 
  const RotaSubtrair = () => {
    router.push("/sub")
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={Styles.fundo}>
        {/* funcao anonima */}
          <button onClick={() => Somar()}>somar</button>
          <p>{soma}</p>
          <button onClick={() => RotaSubtrair()}>ir para subtrair</button>
      </main>
    </>
  )
}

export default Home;